// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type opensnoopEnterArgs struct {
	_     structs.HostLayout
	Fname uint64
	Flags int32
	_     [4]byte
}

// loadOpensnoop returns the embedded CollectionSpec for opensnoop.
func loadOpensnoop() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_OpensnoopBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load opensnoop: %w", err)
	}

	return spec, err
}

// loadOpensnoopObjects loads opensnoop and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*opensnoopObjects
//	*opensnoopPrograms
//	*opensnoopMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadOpensnoopObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadOpensnoop()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// opensnoopSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type opensnoopSpecs struct {
	opensnoopProgramSpecs
	opensnoopMapSpecs
	opensnoopVariableSpecs
}

// opensnoopProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type opensnoopProgramSpecs struct {
	TraceEnterOpen    *ebpf.ProgramSpec `ebpf:"trace_enter_open"`
	TraceEnterOpenat  *ebpf.ProgramSpec `ebpf:"trace_enter_openat"`
	TraceEnterOpenat2 *ebpf.ProgramSpec `ebpf:"trace_enter_openat2"`
	TraceExitOpen     *ebpf.ProgramSpec `ebpf:"trace_exit_open"`
	TraceExitOpenat   *ebpf.ProgramSpec `ebpf:"trace_exit_openat"`
	TraceExitOpenat2  *ebpf.ProgramSpec `ebpf:"trace_exit_openat2"`
}

// opensnoopMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type opensnoopMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
	Starts *ebpf.MapSpec `ebpf:"starts"`
}

// opensnoopVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type opensnoopVariableSpecs struct {
	TargetPid *ebpf.VariableSpec `ebpf:"target_pid"`
}

// opensnoopObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadOpensnoopObjects or ebpf.CollectionSpec.LoadAndAssign.
type opensnoopObjects struct {
	opensnoopPrograms
	opensnoopMaps
	opensnoopVariables
}

func (o *opensnoopObjects) Close() error {
	return _OpensnoopClose(
		&o.opensnoopPrograms,
		&o.opensnoopMaps,
	)
}

// opensnoopMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadOpensnoopObjects or ebpf.CollectionSpec.LoadAndAssign.
type opensnoopMaps struct {
	Events *ebpf.Map `ebpf:"events"`
	Starts *ebpf.Map `ebpf:"starts"`
}

func (m *opensnoopMaps) Close() error {
	return _OpensnoopClose(
		m.Events,
		m.Starts,
	)
}

// opensnoopVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadOpensnoopObjects or ebpf.CollectionSpec.LoadAndAssign.
type opensnoopVariables struct {
	TargetPid *ebpf.Variable `ebpf:"target_pid"`
}

// opensnoopPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadOpensnoopObjects or ebpf.CollectionSpec.LoadAndAssign.
type opensnoopPrograms struct {
	TraceEnterOpen    *ebpf.Program `ebpf:"trace_enter_open"`
	TraceEnterOpenat  *ebpf.Program `ebpf:"trace_enter_openat"`
	TraceEnterOpenat2 *ebpf.Program `ebpf:"trace_enter_openat2"`
	TraceExitOpen     *ebpf.Program `ebpf:"trace_exit_open"`
	TraceExitOpenat   *ebpf.Program `ebpf:"trace_exit_openat"`
	TraceExitOpenat2  *ebpf.Program `ebpf:"trace_exit_openat2"`
}

func (p *opensnoopPrograms) Close() error {
	return _OpensnoopClose(
		p.TraceEnterOpen,
		p.TraceEnterOpenat,
		p.TraceEnterOpenat2,
		p.TraceExitOpen,
		p.TraceExitOpenat,
		p.TraceExitOpenat2,
	)
}

func _OpensnoopClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed opensnoop_bpfeb.o
var _OpensnoopBytes []byte
