// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type execsnoopEnterArgs struct {
	_     structs.HostLayout
	Fname uint64
	Argv  uint64
}

// loadExecsnoop returns the embedded CollectionSpec for execsnoop.
func loadExecsnoop() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ExecsnoopBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load execsnoop: %w", err)
	}

	return spec, err
}

// loadExecsnoopObjects loads execsnoop and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*execsnoopObjects
//	*execsnoopPrograms
//	*execsnoopMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadExecsnoopObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadExecsnoop()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// execsnoopSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type execsnoopSpecs struct {
	execsnoopProgramSpecs
	execsnoopMapSpecs
	execsnoopVariableSpecs
}

// execsnoopProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type execsnoopProgramSpecs struct {
	TraceEnterExecve   *ebpf.ProgramSpec `ebpf:"trace_enter_execve"`
	TraceEnterExecveat *ebpf.ProgramSpec `ebpf:"trace_enter_execveat"`
	TraceExitExecve    *ebpf.ProgramSpec `ebpf:"trace_exit_execve"`
	TraceExitExecveat  *ebpf.ProgramSpec `ebpf:"trace_exit_execveat"`
	TraceProcessExit   *ebpf.ProgramSpec `ebpf:"trace_process_exit"`
	TraceProcessFork   *ebpf.ProgramSpec `ebpf:"trace_process_fork"`
}

// execsnoopMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type execsnoopMapSpecs struct {
	ChildMap *ebpf.MapSpec `ebpf:"child_map"`
	Events   *ebpf.MapSpec `ebpf:"events"`
	Starts   *ebpf.MapSpec `ebpf:"starts"`
}

// execsnoopVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type execsnoopVariableSpecs struct {
	TargetPid *ebpf.VariableSpec `ebpf:"target_pid"`
	TargetUid *ebpf.VariableSpec `ebpf:"target_uid"`
}

// execsnoopObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadExecsnoopObjects or ebpf.CollectionSpec.LoadAndAssign.
type execsnoopObjects struct {
	execsnoopPrograms
	execsnoopMaps
	execsnoopVariables
}

func (o *execsnoopObjects) Close() error {
	return _ExecsnoopClose(
		&o.execsnoopPrograms,
		&o.execsnoopMaps,
	)
}

// execsnoopMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadExecsnoopObjects or ebpf.CollectionSpec.LoadAndAssign.
type execsnoopMaps struct {
	ChildMap *ebpf.Map `ebpf:"child_map"`
	Events   *ebpf.Map `ebpf:"events"`
	Starts   *ebpf.Map `ebpf:"starts"`
}

func (m *execsnoopMaps) Close() error {
	return _ExecsnoopClose(
		m.ChildMap,
		m.Events,
		m.Starts,
	)
}

// execsnoopVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadExecsnoopObjects or ebpf.CollectionSpec.LoadAndAssign.
type execsnoopVariables struct {
	TargetPid *ebpf.Variable `ebpf:"target_pid"`
	TargetUid *ebpf.Variable `ebpf:"target_uid"`
}

// execsnoopPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadExecsnoopObjects or ebpf.CollectionSpec.LoadAndAssign.
type execsnoopPrograms struct {
	TraceEnterExecve   *ebpf.Program `ebpf:"trace_enter_execve"`
	TraceEnterExecveat *ebpf.Program `ebpf:"trace_enter_execveat"`
	TraceExitExecve    *ebpf.Program `ebpf:"trace_exit_execve"`
	TraceExitExecveat  *ebpf.Program `ebpf:"trace_exit_execveat"`
	TraceProcessExit   *ebpf.Program `ebpf:"trace_process_exit"`
	TraceProcessFork   *ebpf.Program `ebpf:"trace_process_fork"`
}

func (p *execsnoopPrograms) Close() error {
	return _ExecsnoopClose(
		p.TraceEnterExecve,
		p.TraceEnterExecveat,
		p.TraceExitExecve,
		p.TraceExitExecveat,
		p.TraceProcessExit,
		p.TraceProcessFork,
	)
}

func _ExecsnoopClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed execsnoop_bpfel.o
var _ExecsnoopBytes []byte
